name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install meson
        run:  |
          sudo apt-get install python3 python3-pip python3-setuptools python3-wheel build-essential g++-9 gcc-9 clang-9 meson ninja-build && pip3 install --user meson
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/c++ 40
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 60
          sudo update-alternatives --config c++

      - uses: actions/checkout@v2
      - name: Build
        run: |
          for d in ./*/ ; do (cd "$d" && mkdir -p build && pwd && mkdir -p include && cd build && meson .. && ninja); done