name: Meson Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install meson
        run:  |
          sudo apt-get install meson ninja-build clang-10 gcc-10
      - uses: actions/checkout@v2
      - name: Build
        run: |
          for d in ./*/ ; do (cd "$d" && mkdir -p build && pwd && mkdir -p include && cd build && meson ..; ninja || echo "Failed"); done