name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install meson
        run: sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build && pip3 install meson

      - uses: actions/checkout@v2
      - name: Build
        run: |
          for d in ./*/ ; do (cd "$d" && mkdir -p build && mkdir -p include && cd build && meson .. && pwd); done